// Package parity reads the oracle files of testdata/parity, generated by
// tools/oracle/gen_model_parity.py with the reference TFLite kernels.
package parity

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
)

// Quantization mirrors the quantization block of the oracle file.
type Quantization struct {
	Scales             []float64 `json:"scales"`
	ZeroPoints         []int64   `json:"zero_points"`
	QuantizedDimension int       `json:"quantized_dimension"`
}

// IO describes the model input or output tensor.
type IO struct {
	Index        int          `json:"index"`
	Name         string       `json:"name"`
	Shape        []int        `json:"shape"`
	DType        string       `json:"dtype"`
	Quantization Quantization `json:"quantization"`
}

// TensorMeta describes a dynamic tensor of the main subgraph.
type TensorMeta struct {
	Name         string       `json:"name"`
	DType        string       `json:"dtype"`
	Quantization Quantization `json:"quantization"`
}

// Step is one invocation: the int8 input frames and the uint8 output produced.
type Step struct {
	Input  []byte `json:"input"`
	Output int    `json:"output"`
}

// Sequence is a run of consecutive invocations starting from freshly reset variables.
type Sequence struct {
	Name  string `json:"name"`
	Steps []Step `json:"steps"`
}

// TraceTensor is the content of one dynamic tensor after a step.
type TraceTensor struct {
	Name  string `json:"name"`
	Shape []int  `json:"shape"`
	DType string `json:"dtype"`
	Data  []byte `json:"data"`
}

// Trace holds every dynamic tensor of the main subgraph after one step of one sequence,
// keyed by tensor index.
type Trace struct {
	Sequence int                 `json:"sequence"`
	Step     int                 `json:"step"`
	Tensors  map[int]TraceTensor `json:"-"`

	RawTensors map[string]TraceTensor `json:"tensors"`
}

// File is one oracle file.
type File struct {
	Model     string             `json:"model"`
	Generator string             `json:"generator"`
	Resolver  string             `json:"resolver"`
	Seed      int64              `json:"seed"`
	Input     IO                 `json:"input"`
	Output    IO                 `json:"output"`
	Tensors   map[int]TensorMeta `json:"-"`
	Sequences []Sequence         `json:"sequences"`
	Traces    []Trace            `json:"traces"`

	RawTensors map[string]TensorMeta `json:"tensors"`
}

// Load reads and decodes an oracle file. Base64 fields are decoded by encoding/json into
// byte slices; string-keyed tensor maps are re-keyed by integer index.
func Load(path string) (*File, error) {
	buf, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var f File
	if err := json.Unmarshal(buf, &f); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if f.Resolver != "BUILTIN_REF" {
		return nil, fmt.Errorf("%s: generated with resolver %q, only BUILTIN_REF is a valid oracle", path, f.Resolver)
	}
	f.Tensors = make(map[int]TensorMeta, len(f.RawTensors))
	for k, v := range f.RawTensors {
		i, err := strconv.Atoi(k)
		if err != nil {
			return nil, fmt.Errorf("%s: tensor key %q: %w", path, k, err)
		}
		f.Tensors[i] = v
	}
	for ti := range f.Traces {
		tr := &f.Traces[ti]
		tr.Tensors = make(map[int]TraceTensor, len(tr.RawTensors))
		for k, v := range tr.RawTensors {
			i, err := strconv.Atoi(k)
			if err != nil {
				return nil, fmt.Errorf("%s: trace %d tensor key %q: %w", path, ti, k, err)
			}
			tr.Tensors[i] = v
		}
		tr.RawTensors = nil
	}
	f.RawTensors = nil
	return &f, nil
}

// Previous returns the trace of the step just before tr in the same sequence, or nil when tr
// is the first step of its sequence or the previous step was not traced.
func (f *File) Previous(tr *Trace) *Trace {
	if tr.Step == 0 {
		return nil
	}
	for i := range f.Traces {
		p := &f.Traces[i]
		if p.Sequence == tr.Sequence && p.Step == tr.Step-1 {
			return p
		}
	}
	return nil
}
